### ISSUE TITLE
Stop video when another start

### ISSUE THREAD

**Issue by AaronKalantarov** [guilhermearaujo/GUIPlayerView#1]
I have an array of url's in tableview.
when i select another video the previous don't stop.
how to fix it?
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
  
  NSLog(@"selected tableview row is %ld",(long)indexPath.row);
  NSLog(@"%@",itemArray);
  
  NSDictionary *item = [itemArray objectAtIndex:indexPath.row];
  NSURL \* urlStream = [NSURL URLWithString:[item objectForKey:@"url"]];
  [playerView setVideoURL:urlStream];
  [playerView prepareAndPlayAutomatically:YES];

}

**Comment by guilhermearaujo** [comment]
When you switch to another video, try running this:

``` objc
[playerView stop];
[playerView setVideoURL:urlStream];
[playerView prepareAndPlayAutomatically:YES];
```

This should work. I will also update the library to do that automatically.

**Comment by AaronKalantarov** [comment]
Tnx! now its work ok.
