### ISSUE TITLE
Using mainBundle

### ISSUE THREAD

**Issue by jimatwood** [guilhermearaujo/GUIPlayerView#2]
Is it possible to use something like NSString *thePath = [NSBundle mainBundle] pathForResource @"BigBuckBunny.mp3" ofType:@"mp4"]; in the GUIPlayerView instead of a remote URL?  I'm trying to write this into an app that doesn't use the internet.  Thank you!

I've made changes to the ViewController.m file but I'm getting a couple of obvious errors in the GUIPlayerView.m file, for example the AVURLAsset section.

Thanks!

**Comment by guilhermearaujo** [comment]
Yes, you can play local videos. If your file is called "BigBuckBunny.mp4", use:

``` objc
NSString *path = [[NSBundle mainBundle] pathForResource @"BigBuckBunny" ofType:@"mp4"];
NSURL *url = [NSURL urlWithString:path];
[player setVideoURL:url];
[player prepareAndPlayAutomatically:<#BOOL#>];
```

**Comment by jimatwood** [comment]
Thank you!  Works fantastic.  Much appreciated.
