### ISSUE TITLE
How to support the RTMP, RTSP protocol live?

### ISSUE THREAD

**Issue by xhzengAIB** [guilhermearaujo/GUIPlayerView#6]
@kamal 
Hi！

HLS Support is very good. But RTMP / RTSP protocal streaming not support playing.

Jack

**Comment by guilhermearaujo** [comment]
Looks like `AVPlayer` does not support RTSP. Some posts on StackOverflow suggest using [Live555](http://www.live555.com) for that.

**Comment by xhzengAIB** [comment]
@guilhermearaujo 
Ok！Thank you!
I will check other some things.

Jack
