### ISSUE TITLE
If the switch video source?

### ISSUE THREAD

**Issue by xhzengAIB** [guilhermearaujo/GUIPlayerView#8]
@guilhermearaujo

**Comment by guilhermearaujo** [comment]
`return YES;`

**Comment by xhzengAIB** [comment]
@guilhermearaujo 

Hi！How should I do?
If i have video list, how i do switch video1、video2 or others.
Thank you for your enthusiastic reply.

Jack

**Comment by guilhermearaujo** [comment]
Check issue #1, see if it helps you.

**Comment by xhzengAIB** [comment]
@guilhermearaujo 
thanks!
